image: node:12-buster

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - yarn install --frozen-lockfile --non-interactive
    - yarn run typecheck
    - yarn run lint
    - yarn run test
    - yarn run build
  artifacts:
    paths:
      - dist/

publish:
  stage: deploy
  only:
    refs:
      - master
  script:
    - npx @manuscripts/publish


.publish_manually_def: &publish_manually_def
  stage: deploy
  script:
    - npx @manuscripts/publish


publish_manually:
  <<: *publish_manually_def
  when: manual
