image: node:12-buster

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - yarn install --frozen-lockfile --non-interactive
    - yarn run typecheck
    - yarn run lint
    - yarn run test
    - yarn run build
  artifacts:
    paths:
      - dist/

publish:
  stage: deploy
  only:
    refs:
      - master
  script:
    - npx @manuscripts/publish


.deploy_development_def: &deploy_development_def
  stage: deploy
  environment:
    name: development
    url: https://api-dev.manuscripts.io
  script:
    - yarn install --frozen-lockfile --non-interactive


publish_manually:
  <<: *deploy_development_def
  when: manual
