/*!
 * © 2025 Atypon Systems LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { BibliographyItemType } from '@manuscripts/transform'

export const bibliographyItemTypes: [BibliographyItemType, string][] = [
  ['article-journal', 'Journal Article'],
  ['book', 'Book'],
  ['chapter', 'Chapter'],
  ['paper-conference', 'Conference Paper'],
  ['thesis', 'Thesis'],
  ['webpage', 'Web Page'],
  ['other', 'Other'],
  ['standard', 'Standard'],
  ['dataset', 'Dataset'],
  ['preprint', 'Preprint'],
]

interface FieldConfigObject {
  [fieldName: string]: {
    [key in BibliographyItemType]: boolean
  }
}

export const fieldConfigObject: FieldConfigObject = {
  author: {
    'article-journal': true,
    book: true,
    chapter: true,
    'paper-conference': true,
    dataset: true,
    preprint: true,
    standard: false,
    thesis: true,
    webpage: true,
    other: true,
  },
  editor: {
    'article-journal': false,
    book: true,
    chapter: true,
    'paper-conference': false,
    dataset: false,
    preprint: false,
    standard: false,
    thesis: false,
    webpage: false,
    other: false,
  },
  title: {
    'article-journal': true,
    book: true,
    chapter: true,
    'paper-conference': true,
    dataset: true,
    preprint: true,
    standard: false,
    thesis: true,
    webpage: true,
    other: true,
  },
  std: {
    'article-journal': false,
    book: false,
    chapter: false,
    'paper-conference': false,
    dataset: false,
    preprint: false,
    standard: true,
    thesis: false,
    webpage: false,
    other: false,
  },
  issued: {
    'article-journal': true,
    book: true,
    chapter: true,
    'paper-conference': true,
    dataset: true,
    preprint: true,
    standard: false,
    thesis: true,
    webpage: true,
    other: true,
  },
  'container-title': {
    'article-journal': true,
    book: true,
    chapter: true,
    'paper-conference': false,
    dataset: true,
    preprint: true,
    standard: true,
    thesis: false,
    webpage: false,
    other: true,
  },
  'collection-title': {
    'article-journal': false,
    book: true,
    chapter: true,
    'paper-conference': false,
    dataset: false,
    preprint: false,
    standard: false,
    thesis: false,
    webpage: false,
    other: false,
  },
  volume: {
    'article-journal': true,
    book: true,
    chapter: true,
    'paper-conference': false,
    dataset: false,
    preprint: false,
    standard: false,
    thesis: false,
    webpage: false,
    other: false,
  },
  issue: {
    'article-journal': true,
    book: false,
    chapter: false,
    'paper-conference': false,
    dataset: false,
    preprint: false,
    standard: false,
    thesis: false,
    webpage: false,
    other: false,
  },
  supplement: {
    'article-journal': true,
    book: false,
    chapter: false,
    'paper-conference': false,
    dataset: false,
    preprint: false,
    standard: false,
    thesis: false,
    webpage: false,
    other: false,
  },
  edition: {
    'article-journal': false,
    book: true,
    chapter: true,
    'paper-conference': false,
    dataset: false,
    preprint: false,
    standard: false,
    thesis: false,
    webpage: false,
    other: false,
  },
  'publisher-place': {
    'article-journal': false,
    book: true,
    chapter: true,
    'paper-conference': true,
    dataset: true,
    preprint: false,
    standard: false,
    thesis: false,
    webpage: true,
    other: true,
  },
  publisher: {
    'article-journal': false,
    book: true,
    chapter: true,
    'paper-conference': true,
    dataset: true,
    preprint: false,
    standard: false,
    thesis: false,
    webpage: true,
    other: true,
  },
  event: {
    'article-journal': false,
    book: false,
    chapter: false,
    'paper-conference': true,
    dataset: false,
    preprint: false,
    standard: false,
    thesis: false,
    webpage: false,
    other: false,
  },
  'event-date': {
    'article-journal': false,
    book: false,
    chapter: false,
    'paper-conference': true,
    dataset: false,
    preprint: false,
    standard: false,
    thesis: false,
    webpage: false,
    other: false,
  },
  'event-place': {
    'article-journal': false,
    book: false,
    chapter: false,
    'paper-conference': true,
    dataset: false,
    preprint: false,
    standard: false,
    thesis: false,
    webpage: false,
    other: false,
  },
  institution: {
    'article-journal': false,
    book: false,
    chapter: false,
    'paper-conference': false,
    dataset: false,
    preprint: false,
    standard: false,
    thesis: true,
    webpage: false,
    other: false,
  },
  page: {
    'article-journal': true,
    book: true,
    chapter: true,
    'paper-conference': true,
    dataset: false,
    preprint: false,
    standard: false,
    thesis: false,
    webpage: false,
    other: false,
  },
  elocationID: {
    'article-journal': true,
    book: false,
    chapter: false,
    'paper-conference': false,
    dataset: false,
    preprint: true,
    standard: false,
    thesis: false,
    webpage: false,
    other: false,
  },
  links: {
    // type: ext-link
    'article-journal': true,
    book: true,
    chapter: true,
    'paper-conference': true,
    dataset: true,
    preprint: true,
    standard: true,
    thesis: true,
    webpage: true,
    other: true,
  },
  'number-of-pages': {
    'article-journal': false,
    book: true,
    chapter: true,
    'paper-conference': false,
    dataset: false,
    preprint: false,
    standard: false,
    thesis: true,
    webpage: false,
    other: false,
  },
  accessed: {
    'article-journal': false,
    book: false,
    chapter: false,
    'paper-conference': false,
    dataset: true,
    preprint: false,
    standard: false,
    thesis: false,
    webpage: true,
    other: false,
  },
  comment: {
    'article-journal': true,
    book: true,
    chapter: true,
    'paper-conference': false,
    dataset: true,
    preprint: false,
    standard: false,
    thesis: true,
    webpage: false,
    other: true,
  },
  DOI: {
    'article-journal': true,
    book: true,
    chapter: true,
    'paper-conference': true,
    dataset: true,
    preprint: true,
    standard: false,
    thesis: true,
    webpage: false,
    other: false,
  },
  URL: {
    'article-journal': true,
    book: true,
    chapter: true,
    'paper-conference': true,
    dataset: true,
    preprint: true,
    standard: false,
    thesis: true,
    webpage: false,
    other: false,
  },
}
